# Generated by Django 6.0.1 on 2026-01-26 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_administrativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitador',
            fields=[
                ('id_facilitador', models.AutoField(primary_key=True, serialize=False)),
                ('id_estatu', models.ForeignKey(blank=True, db_column='id_estatu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitadores', to='gestion_administrativa.estatu')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.RESTRICT, related_name='facilitadores', to='gestion_administrativa.persona')),
            ],
            options={
                'db_table': 'Facilitador',
                'permissions': [('ver_secciones', 'Puede ver sus secciones/ofertas asignadas'), ('cargar_notas', 'Puede cargar notas'), ('solicitar_cambio_nota', 'Puede solicitar cambio de nota'), ('seleccionar_asignaturas', 'Puede seleccionar asignaturas a dictar'), ('gestionar_disponibilidad', 'Puede registrar disponibilidad (día/hora)')],
            },
        ),
        migrations.CreateModel(
            name='Asignaturas_has_Facilitador',
            fields=[
                ('id_asignaturas_has_Facilitador', models.AutoField(primary_key=True, serialize=False)),
                ('cupos', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('presencial', models.BooleanField(default=True)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.RESTRICT, related_name='facilitadores_asignados', to='gestion_administrativa.asignatura')),
                ('id_facilitador', models.ForeignKey(db_column='id_facilitador', on_delete=django.db.models.deletion.RESTRICT, related_name='asignaturas_asignadas', to='profesor.facilitador')),
            ],
            options={
                'db_table': 'Asignaturas_has_Facilitador',
            },
        ),
        migrations.CreateModel(
            name='Facilitador_has_Contrato',
            fields=[
                ('id_facilitador_contrato', models.BigAutoField(primary_key=True, serialize=False)),
                ('horas_academicas', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_contrato', models.ForeignKey(db_column='id_tipo_Contrato', on_delete=django.db.models.deletion.RESTRICT, related_name='facilitadores_contrato', to='gestion_administrativa.tipo_contrato')),
                ('id_estatu', models.ForeignKey(blank=True, db_column='id_estatu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitador_contratos', to='gestion_administrativa.estatu')),
                ('id_facilitador', models.ForeignKey(db_column='id_facilitador', on_delete=django.db.models.deletion.RESTRICT, related_name='contratos', to='profesor.facilitador')),
            ],
            options={
                'db_table': 'Facilitador_has_Contrato',
                'constraints': [models.UniqueConstraint(fields=('id_facilitador', 'id_contrato', 'fecha_inicio'), name='uq_phc')],
            },
        ),
    ]
