# Generated by Django 6.0.1 on 2026-01-26 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitador',
            options={'permissions': [('ver_secciones', 'Puede ver sus secciones/ofertas asignadas'), ('cargar_notas', 'Puede cargar notas'), ('solicitar_cambio_nota', 'Puede solicitar cambio de nota'), ('seleccionar_asignaturas', 'Puede seleccionar asignaturas a dictar'), ('gestionar_disponibilidad', 'Puede registrar disponibilidad (día/hora)'), ('ver_lista_participantes', 'Puede ver e imprimir lista de participantes por materia')]},
        ),
    ]
