# Generated by Django 6.0.1 on 2026-01-27 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_alter_facilitador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facilitador',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='facilitador',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
