# Generated by Django 6.0.1 on 2026-01-26 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_administrativa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to='gestion_administrativa.persona')),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_usuario',
                'permissions': [('gestionar_usuarios', 'Puede gestionar usuarios'), ('asignar_roles', 'Puede asignar roles'), ('asignar_admin', 'Puede asignar el rol Administrativo (solo Master)'), ('ver_auditoria', 'Puede ver auditoría'), ('exportar_auditoria', 'Puede exportar auditoría'), ('ver_logs_acceso', 'Puede ver logs de acceso')],
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=80)),
                ('entidad', models.CharField(blank=True, max_length=80, null=True)),
                ('llave', models.CharField(blank=True, max_length=120, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('id_persona', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='gestion_administrativa.persona')),
            ],
            options={
                'db_table': 'Auditoria',
                'indexes': [models.Index(fields=['fecha_evento'], name='idx_audit_fecha')],
            },
        ),
        migrations.CreateModel(
            name='PersonaHasRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to='gestion_administrativa.persona')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.RESTRICT, related_name='personas_asignadas', to='seguridad.roles')),
            ],
            options={
                'db_table': 'Persona_has_Roles',
                'constraints': [models.UniqueConstraint(fields=('id_persona', 'id_rol'), name='pk_phr')],
            },
        ),
        migrations.CreateModel(
            name='RolesHasPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='seguridad.permisos')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='roles_permisos', to='seguridad.roles')),
            ],
            options={
                'db_table': 'Roles_has_Permisos',
                'constraints': [models.UniqueConstraint(fields=('id_rol', 'id_permiso'), name='pk_rhp')],
            },
        ),
    ]
