# Generated by Django 6.0.1 on 2026-01-26 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_administrativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('unidades_cred_aprobadas', models.IntegerField(default=0)),
                ('unidades_cred_cursadas', models.IntegerField(default=0)),
                ('unidades_cred_reprobadas', models.IntegerField(default=0)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_carrera', models.ForeignKey(blank=True, db_column='id_carrera', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_compat', to='gestion_administrativa.carrera')),
                ('id_estatu', models.ForeignKey(blank=True, db_column='id_estatu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='gestion_administrativa.estatu')),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.RESTRICT, related_name='estudiantes', to='gestion_administrativa.persona')),
            ],
            options={
                'db_table': 'Estudiante',
                'permissions': [('inscribir', 'Puede realizar inscripción'), ('ver_horario', 'Puede ver su horario'), ('ver_record', 'Puede ver su récord académico'), ('generar_constancia', 'Puede generar/descargar constancia')],
            },
        ),
        migrations.CreateModel(
            name='Estudiantes_has_Carreras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.RESTRICT, related_name='estudiantes_por_carrera', to='gestion_administrativa.carrera')),
                ('id_estatu', models.ForeignKey(blank=True, db_column='id_estatu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante_carreras', to='gestion_administrativa.estatu')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.RESTRICT, related_name='carreras', to='participante.estudiante')),
            ],
            options={
                'db_table': 'Estudiantes_has_Carreras',
                'constraints': [models.UniqueConstraint(fields=('id_estudiante', 'id_carrera'), name='uq_estudiante_carrera')],
            },
        ),
        migrations.CreateModel(
            name='Materia_Inscrita',
            fields=[
                ('id_materia_inscrita', models.BigAutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(blank=True, max_length=20, null=True)),
                ('horario_inicio', models.DateTimeField(blank=True, null=True)),
                ('horario_fin', models.DateTimeField(blank=True, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.RESTRICT, related_name='inscripciones', to='gestion_administrativa.asignatura')),
                ('id_estudiante', models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.RESTRICT, related_name='inscripciones', to='participante.estudiante')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.RESTRICT, related_name='inscripciones', to='gestion_administrativa.periodo_academico')),
            ],
            options={
                'db_table': 'Materia_Inscrita',
                'indexes': [models.Index(fields=['id_estudiante', 'id_periodo'], name='idx_mi_estudiante_periodo'), models.Index(fields=['id_periodo'], name='idx_mi_periodo')],
                'constraints': [models.UniqueConstraint(fields=('id_estudiante', 'id_asignatura', 'id_periodo'), name='uq_mi_est_asig_per'), models.CheckConstraint(condition=models.Q(('nota__isnull', True), models.Q(('nota__gte', 1.0), ('nota__lte', 5.0)), _connector='OR'), name='ck_nota_rango'), models.CheckConstraint(condition=models.Q(('horario_inicio__isnull', True), ('horario_fin__isnull', True), ('horario_fin__gt', models.F('horario_inicio')), _connector='OR'), name='ck_horario_mi')],
            },
        ),
    ]
