# Generated by Django 6.0.1 on 2026-01-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'permissions': [('inscribir', 'Puede realizar inscripción'), ('ver_horario', 'Puede ver su horario'), ('ver_record', 'Puede ver su récord académico'), ('ver_constancia', 'Puede generar/descargar constancia de estudio'), ('ver_promedio', 'Puede consultar promedio')]},
        ),
    ]
