# Generated by Django 6.0.1 on 2026-01-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0002_alter_estudiante_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
