# Generated by Django 6.0.1 on 2026-01-27 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0003_estudiante_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
    ]
