# Generated by Django 6.0.1 on 2026-01-27 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativa', '0005_persona_sexo'),
        ('participante', '0004_alter_estudiante_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='id_mencion',
            field=models.ForeignKey(blank=True, db_column='id_mencion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='gestion_administrativa.mencion'),
        ),
        migrations.AddField(
            model_name='estudiantes_has_carreras',
            name='id_mencion',
            field=models.ForeignKey(blank=True, db_column='id_mencion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante_carreras', to='gestion_administrativa.mencion'),
        ),
    ]
