# Generated by Django 6.0.1 on 2026-01-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0005_estudiante_id_mencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='id_estatu',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
