# Generated by Django 6.0.1 on 2026-01-26 22:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Carrera',
            },
        ),
        migrations.CreateModel(
            name='estatu',
            fields=[
                ('id_estatu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'estatu',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('cedula', models.IntegerField(unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Persona',
            },
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id_piso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Piso',
            },
        ),
        migrations.CreateModel(
            name='Temp_Asignaturas_has_Facilitador_has_aula',
            fields=[
                ('id_asignaturas_has_Facilitador_has_aula', models.AutoField(primary_key=True, serialize=False)),
                ('horario_inicio', models.DateTimeField()),
                ('horario_fin', models.DateTimeField()),
                ('seccion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Temp_Asignaturas_has_Facilitador_has_aula',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Contrato',
            fields=[
                ('id_tipo_Contrato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Tipo_Contrato',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Materia',
            fields=[
                ('id_tipo_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'Tipo_Materia',
            },
        ),
        migrations.CreateModel(
            name='Mencion',
            fields=[
                ('id_mencion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.RESTRICT, related_name='Mencion_set', to='gestion_administrativa.carrera')),
            ],
            options={
                'db_table': 'Mencion',
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('unidades_credito', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('id_mencion', models.ForeignKey(db_column='id_mencion', on_delete=django.db.models.deletion.RESTRICT, related_name='Asignatura_set', to='gestion_administrativa.mencion')),
            ],
            options={
                'db_table': 'Asignatura',
            },
        ),
        migrations.CreateModel(
            name='Periodo_Academico',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('id_estatu', models.ForeignKey(blank=True, db_column='id_estatu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Periodo_Academico_set', to='gestion_administrativa.estatu')),
            ],
            options={
                'db_table': 'Periodo_Academico',
            },
        ),
        migrations.CreateModel(
            name='aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('capacidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estatus', models.BooleanField(default=True)),
                ('id_piso', models.ForeignKey(db_column='id_piso', on_delete=django.db.models.deletion.RESTRICT, related_name='aula_set', to='gestion_administrativa.piso')),
            ],
            options={
                'db_table': 'aula',
            },
        ),
        migrations.CreateModel(
            name='Prelaciones',
            fields=[
                ('id_prelacion', models.AutoField(primary_key=True, serialize=False)),
                ('id_asignatura', models.ForeignKey(db_column='id_asignatura', on_delete=django.db.models.deletion.CASCADE, related_name='Prelaciones_de_set', to='gestion_administrativa.asignatura')),
                ('id_asignatura_antecesora', models.ForeignKey(db_column='id_asignatura_antecesora', on_delete=django.db.models.deletion.RESTRICT, related_name='Prelaciones_antecesora_set', to='gestion_administrativa.asignatura')),
            ],
            options={
                'db_table': 'Prelaciones',
            },
        ),
    ]
