# Generated by Django 6.0.1 on 2026-01-26 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_administrativa', '0001_initial'),
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_asignaturas_has_facilitador_has_aula',
            name='id_asignaturas_has_facilitador',
            field=models.ForeignKey(db_column='id_asignaturas_has_facilitador', on_delete=django.db.models.deletion.RESTRICT, related_name='Temp_ofertas_set', to='profesor.asignaturas_has_facilitador'),
        ),
        migrations.AddField(
            model_name='temp_asignaturas_has_facilitador_has_aula',
            name='id_aula',
            field=models.ForeignKey(db_column='id_aula', on_delete=django.db.models.deletion.RESTRICT, related_name='Temp_ofertas_set', to='gestion_administrativa.aula'),
        ),
        migrations.AddField(
            model_name='temp_asignaturas_has_facilitador_has_aula',
            name='id_facilitador',
            field=models.ForeignKey(db_column='id_facilitador', on_delete=django.db.models.deletion.RESTRICT, related_name='Temp_ofertas_set', to='profesor.facilitador'),
        ),
        migrations.AddField(
            model_name='temp_asignaturas_has_facilitador_has_aula',
            name='id_periodo',
            field=models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.RESTRICT, related_name='Temp_ofertas_set', to='gestion_administrativa.periodo_academico'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='id_tipo_materia',
            field=models.ForeignKey(db_column='id_tipo_materia', on_delete=django.db.models.deletion.RESTRICT, related_name='Asignatura_set', to='gestion_administrativa.tipo_materia'),
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(fields=('id_piso', 'nombre'), name='uq_aula'),
        ),
        migrations.AddConstraint(
            model_name='prelaciones',
            constraint=models.UniqueConstraint(fields=('id_asignatura',), name='uq_prel_unica'),
        ),
        migrations.AddConstraint(
            model_name='prelaciones',
            constraint=models.CheckConstraint(condition=models.Q(('id_asignatura', models.F('id_asignatura_antecesora')), _negated=True), name='ck_no_ciclo'),
        ),
        migrations.AddIndex(
            model_name='temp_asignaturas_has_facilitador_has_aula',
            index=models.Index(fields=['id_periodo'], name='idx_temp_periodo'),
        ),
        migrations.AddIndex(
            model_name='temp_asignaturas_has_facilitador_has_aula',
            index=models.Index(fields=['id_asignaturas_has_facilitador'], name='idx_temp_asigprof'),
        ),
        migrations.AddConstraint(
            model_name='temp_asignaturas_has_facilitador_has_aula',
            constraint=models.CheckConstraint(condition=models.Q(('horario_fin__gt', models.F('horario_inicio'))), name='ck_horario_temp'),
        ),
        migrations.AddConstraint(
            model_name='temp_asignaturas_has_facilitador_has_aula',
            constraint=models.UniqueConstraint(fields=('id_asignaturas_has_facilitador', 'id_periodo', 'seccion'), name='uq_oferta_seccion'),
        ),
    ]
