# Generated by Django 6.0.1 on 2026-01-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativa', '0003_gist_exclusions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estatu',
            options={'permissions': [('ver_componentes', 'Puede ver componentes (Gestión Administrativa)'), ('crear_componentes', 'Puede crear componentes (Gestión Administrativa)'), ('editar_componentes', 'Puede editar componentes (Gestión Administrativa)'), ('eliminar_componentes', 'Puede eliminar componentes (Gestión Administrativa)')]},
        ),
    ]
