# Generated by Django 6.0.1 on 2026-01-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativa', '0004_alter_estatu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
