# Generated by Django 6.0.1 on 2026-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativa', '0005_persona_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO'), ('I', 'INDEFINIDO')], default='I', max_length=1),
        ),
    ]
